name: Build and Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Haxelib dependencies
      run: |
        haxelib newrepo
        haxelib install hxcpp > /dev/null
        haxelib install lime > /dev/null
        haxelib install openfl > /dev/null
        haxelib install flixel > /dev/null
        haxelib set lime $(haxelib list lime | grep lime)
        haxelib set openfl $(haxelib list openfl | grep openfl)
        haxelib set flixel $(haxelib list flixel | grep flixel)

    - name: Build HTML5
      run: |
        haxelib run lime build html5 -final

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push build files
      run: |
        if [ -d "build/html5" ]; then
          git add build/html5 -f
          git diff --cached --quiet || (git commit -m "Auto-build: Compile HaxeFlixel for HTML5 [skip ci]" && git push)
        else
          echo "Build directory not found"
          exit 1
        fi
      continue-on-error: true
